### ISSUE TITLE
] Failed to fetch Makefile from URL

### ISSUE THREAD

**Issue by cntvro** [PaserTech-Hardware/armbian-zc-328#1]
[🌱] Configuration prepared for BOARD build [ zc-328.conf ]
[✨] Repeat Build Options (early) [ ./compile.sh build BOARD=zc-328 BRANCH=current BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no NO_HOST_RELEASE_CHECK=yes RELEASE=jammy ]
[🌱] Checked directory OK for mount options [ /home/zsj/build/.tmp ('main temporary dir') ]
[🌱] Preparing [ host ]
[🌱] Syncing clock [ host ]
[🔨]   11 Apr 12:32:45 ntpdate[61449]: adjust time server 202.112.29.82 offset -0.002372 sec
[🌱] Ignoring toolchains [ SKIP_EXTERNAL_TOOLCHAINS: yes ]
[🌱] Aggregating packages [ rootfs ]
[🌱] Python3 version [ 3.10.12 - 'Python 3.10.12' ]
[🌱] pip3 version [ 22.0.2: 'pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)' ]
[🌱] Using cached pip packages for Python tools [ f34c3f616841e80aed6efe6a93e040ed3439314113e5f028c99e76c254e166ba ]
[🔨]   Summary: Aggregation: debootstrap: 5; rootfs: 54; image: 0; desktop: 0; apt-sources: 0; hash: 57a41ce0b67e59a7
[🌱] artifact [ uboot :: uboot() ]
[🌱] Producing new & caching [ GIT_INFO_UBOOT ]
[🌱] Fetching SHA1 of 'tag' 'refs/heads/v2022.04^{}' [ https://github.com/u-boot/u-boot ]
[🌱] SHA1 of tag refs/heads/v2022.04^{} [ '' ]
[🌱] Failed to fetch SHA1 of 'tag' 'refs/heads/v2022.04^{}' [ https://github.com/u-boot/u-boot ]
[🌱] Fetching SHA1 of 'tag' 'refs/heads/v2022.04' [ https://github.com/u-boot/u-boot ]
[🌱] SHA1 of tag refs/heads/v2022.04 [ '' ]
[🌱] Failed to fetch SHA1 of 'tag' 'refs/heads/v2022.04' [ https://github.com/u-boot/u-boot ]
[🌱] Fetching SHA1 of 'tag' 'v2022.04^{}' [ https://github.com/u-boot/u-boot ]
[🌱] SHA1 of tag v2022.04^{} [ 'e4b6ebd3de982ae7185dbf689a030e73fd06e0d2' ]
[🚸] Failed to fetch Makefile from URL [ https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[🚸] Command failed, retrying in 5s [ obtain_makefile_body_from_url https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[🚸] Failed to fetch Makefile from URL [ https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[🚸] Command failed, retrying in 5s [ obtain_makefile_body_from_url https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[🚸] Failed to fetch Makefile from URL [ https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[🚸] Command failed, retrying in 5s [ obtain_makefile_body_from_url https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[🚸] Failed to fetch Makefile from URL [ https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[🚸] Command failed, retrying in 5s [ obtain_makefile_body_from_url https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[🚸] Failed to fetch Makefile from URL [ https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[🚸] Command failed, retrying in 5s [ obtain_makefile_body_from_url https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[🚸] Command failed 5 times, giving up [ obtain_makefile_body_from_url https://raw.githubusercontent.com/u-boot/u-boot/e4b6ebd3de982ae7185dbf689a030e73fd06e0d2/Makefile ]
[💥] Error 1 occurred in main shell [ at /home/zsj/build/lib/functions/general/git-ref2info.sh:144
   obtain_makefile_body_from_git() --> lib/functions/general/git-ref2info.sh:144
       memoized_git_ref_to_info() --> lib/functions/general/git-ref2info.sh:196
                   run_memoized() --> lib/functions/general/memoize-cached.sh:69
   artifact_uboot_prepare_version() --> lib/functions/artifacts/artifact-uboot.sh:44
       artifact_prepare_version() --> lib/functions/artifacts/artifacts-obtain.sh:34
                do_with_logging() --> lib/functions/logging/section-logging.sh:81
       obtain_complete_artifact() --> lib/functions/artifacts/artifacts-obtain.sh:88
       build_artifact_for_image() --> lib/functions/artifacts/artifacts-obtain.sh:392
    main_default_build_packages() --> lib/functions/main/build-packages.sh:108
   full_build_packages_rootfs_and_image() --> lib/functions/main/default-build.sh:31
          do_with_default_build() --> lib/functions/main/default-build.sh:42
         cli_standard_build_run() --> lib/functions/cli/cli-build.sh:25
        armbian_cli_run_command() --> lib/functions/cli/utils-cli.sh:136
                 cli_entrypoint() --> lib/functions/cli/entrypoint.sh:176
                           main() --> ./compile.sh:50
 ]
[💥] Cleaning up [ please wait for cleanups to finish ]
[🌿] ANSI log file built; inspect it by running: [ less -RS output/logs/log-build-78773662-4b70-45cb-9eb6-4aa0e97dce62.log.ans ]
[🌿] Share log manually (or SHARE_LOG=yes): [ curl --data-binary @output/logs/log-build-78773662-4b70-45cb-9eb6-4aa0e97dce62.log.ans https://paste.armbian.com/log ]

**Comment by Angelic47** [comment]
Hello, 
This seems be a network issue, as armbian will download source code when you compile the image.  
Please check your network connection to raw.githubusercontent.com and try again.

**Comment by cntvro** [comment]
> Hello, This seems be a network issue, as armbian will download source code when you compile the image. Please check your network connection to raw.githubusercontent.com and try again.

Thank you, I'll try again.

**Comment by cntvro** [comment]
I succeeded at six in the morning.

**Comment by Angelic47** [comment]
:D well done! Glad to hear your success!
