### ISSUE TITLE
build process it successfully，but TTL display was wrong.

### ISSUE THREAD

**Issue by cntvro** [PaserTech-Hardware/armbian-zc-328#2]
![ZC-328](https://github.com/PaserTech-Hardware/armbian-zc-328/assets/3983446/e4c02e6a-5967-40df-9e92-efcb1d94e0b5)

I  build process it successfully.（Armbian-unofficial_24.5.0-trunk_Zc-328_jammy_current_6.1.85.img ）
However, after writing, the system did not start normally, and the TTL display was wrong.
Have any brothers succeeded? Can you share the img firmware?
Thank you!

编译成功后写入启动不了，TTL跑马报错。有兄弟成功的吗，能否分享一下固件。不胜感激！

`Channel a: DDR3 400MHz
Bus Width=32 Col=10 Bank=8 Row=15 CS=1 Die Bus-Width=8 Size=1024MB
Channel b: DDR3 400MHz
Bus Width=32 Col=10 Bank=8 Row=15 CS=1 Die Bus-Width=8 Size=1024MB
Memory OK
Memory OK
OUT

U-Boot 2014.10-RK3288-06-02172-g9ae856e-dirty (Jan 17 2017 - 13:46:20)

CPU: rk3288
cpu version = 0
CPU's clock information:
    arm pll = 816000000HZ
    periph pll = 297000000HZ
    ddr pll = 396000000HZ
    codec pll = 384000000HZ
Board:  Rockchip platform Board
DRAM:  Found dram banks: 1
Adding bank:0000000000000000(0000000080000000)
128 MiB
GIC CPU mask = 0x00000001
SdmmcInit = 0 400
SdmmcInit = 2 0
ERROR: v7_dcache_inval_range - start address is not aligned - 0x059bbc8c
ERROR: v7_dcache_inval_range - stop address is not aligned - 0x059bbe8c
ERROR: v7_dcache_inval_range - start address is not aligned - 0x059cba8c
ERROR: v7_dcache_inval_range - stop address is not aligned - 0x059cbc8c
ERROR: v7_dcache_inval_range - start address is not aligned - 0x059bbc8c
ERROR: v7_dcache_inval_range - stop address is not aligned - 0x059bbe8c
ERROR: v7_dcache_inval_range - start address is not aligned - 0x059cba8c
ERROR: v7_dcache_inval_range - stop address is not aligned - 0x059cbc8c
ERROR: v7_dcache_inval_range - start address is not aligned - 0x059bbc8c
ERROR: v7_dcache_inval_range - stop address is not aligned - 0x059bbe8c
ERROR: v7_dcache_inval_range - start address is not aligned - 0x059cba8c
ERROR: v7_dcache_inval_range - stop address is not aligned - 0x059cbc8c
ERROR: v7_dcache_inval_range - start address is not aligned - 0x059bbc8c
ERROR: v7_dcache_inval_range - stop address is not aligned - 0x059bbe8c
ERROR: v7_dcache_inval_range - start address is not aligned - 0x059cba8c
ERROR: v7_dcache_inval_range - stop address is not aligned - 0x059cbc8c
ERROR: v7_dcache_inval_range - start address is not aligned - 0x059bbc8c
ERROR: v7_dcache_inval_range - stop address is not aligned - 0x059cbc8c
storage init OK!
Using default environment

GetParam
Load FDT from resource image.
power key: bank-16777215 pin-255
i2c_get_bus_num_fdt: Can't find any matched I2C bus
i2c_set_bus_num: I2C bus error!
I2C bus error, PLS set i2c bus first!
I2C bus error, PLS set i2c bus first!
No pmic detect.
can't find dts node for pwm1
set pwm voltage ok,pwm_id =1 vol=1100000,pwm_value=52
SecureBootEn = 0, SecureBootLock = 0

#Boot ver: 2017-01-17#2.30
empty serial no.
normal boot.
checkKey
vbus = 0
no fuel gauge found
no fuel gauge found
read logo on state from dts [0]
no fuel gauge found
Hit any key to stop autoboot:  0
bad image magic.
load boot image failed
ERROR: [rk_load_image_from_storage]: bootrk: bad boot or kernel image
Unable to boot:boot
try to start recovery
bad image magic.
load boot image failed
ERROR: [rk_load_image_from_storage]: bootrk: bad boot or kernel image
Unable to boot:recovery
try to start backup
bad image magic.
load boot image failed
ERROR: [rk_load_image_from_storage]: bootrk: bad boot or kernel image
Unable to boot:backup
try to start rockusb
`

**Comment by Angelic47** [comment]
Hi, 
According to your boot logs, this is DEFINITELY not your armbian image you just compiled. 
The reason is quite simple: It shows U-Boot 2014, which not possible belongs to armbian since we are using v2022 and later. 

For some reasons you might flashed a wrong firmware, or just nothing - it's still the original firmware provided by the manufacturer in eMMC. 

Please try the following command to erase the whole flash (must enter the maskrom mode and download the boot first): 
```
/home/username/armbian/build/cache/sources/rkbin-tools/tools/rkdeveloptool ef
```
Then flash your image, and try again. 

Hope this will be helpful for you!

**Comment by cntvro** [comment]
Thank you. I'll try again.
